// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_Railroad_City_IntegrationTest.#TestCanGenerateASingleRailroad()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_Railroad_City_IntegrationTest.#TestCanGenerateASingleRailroad()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "RouteCalculator.IntegrationTest.RailroadMap_Railroad_City_IntegrationTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "RouteCalculator.IntegrationTest.Specifications_And_Route_IntegrationTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "RouteCalculator.IntegrationTest.Specifications_And_Route_IntegrationTest.#TestIfAndSpecDistanceSpecAndOriginSpecCanSpecifyARoute(System.Boolean,System.String[],System.Int32,System.Int32,System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.Specifications_And_Route_IntegrationTest.#TestIfAndSpecDistanceSpecAndOriginSpecCanSpecifyARoute(System.Boolean,System.String[],System.Int32,System.Int32,System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "RouteCalculator.IntegrationTest.Specification_Route_IntegrationTest`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "RouteCalculator.IntegrationTest.Specification_Route_IntegrationTest`1.#testArguments")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dest", Scope = "type", Target = "RouteCalculator.IntegrationTest.AndSpec_OriginDestSpec_DistanceSpec_Route_IntegrationTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "RouteCalculator.IntegrationTest.AndSpec_OriginDestSpec_DistanceSpec_Route_IntegrationTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.AndSpec_OriginDestSpec_DistanceSpec_Route_IntegrationTest.#TestIfAndSpecDistanceSpecAndOriginSpecCanSpecifyARoute(System.String[],System.Int32,System.Int32,System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.AndSpec_OriginDestSpec_DistanceSpec_Route_IntegrationTest.#TestIfMightTestHelperGetsCorrectResults(System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.AndSpec_OriginDestSpec_DistanceSpec_Route_IntegrationTest.#TestIfTestHelperGetsCorrectResults(System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.AndSpec_OriginDestSpec_DistanceSpec_Route_IntegrationTest.#TestIfMightTestHelperGetsCorrectResults(System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.AndSpec_OriginDestSpec_DistanceSpec_Route_IntegrationTest.#TestIfTestHelperGetsCorrectResults(System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_RouteFinder_ISpecificationImplementations_IntegrationTest.#TestIfRouteFinderExecutesCompoundSingleResultSpecifications(System.String,System.String,System.Type[],System.Object[][])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_RouteFinder_ISpecificationImplementations_IntegrationTest.#TestIfRouteFinderExecuteSimpleSingleResultSpecifications(System.Type,System.String,System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_RouteFinder_ISpecificationImplementations_SingleResults_IntegrationTest.#TestIfRouteFinderExecutesCompoundSingleResultSpecifications(System.String,System.String,System.Type[],System.Object[][])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_RouteFinder_ISpecificationImplementations_SingleResults_IntegrationTest.#TestIfRouteFinderExecuteSimpleSingleResultSpecifications(System.Type,System.String,System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_Route_RouteFinder_Specifications_MultipleResults_IntegrationTest.#TestIfRouteFinderCanFindAllRoutesThatComplyWithACompositeSpec(System.String,System.String[],System.Type[],System.Object[][])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "RouteCalculator.IntegrationTest.RailroadMap_RouteFinder_ISpecificationImplementations_SingleResults_IntegrationTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ctors", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_RouteFinder_ISpecificationImplementations_SingleResults_IntegrationTest.#TestIfRouteFinderExecutesCompoundSingleResultSpecifications(System.String,System.String,System.Type[],System.Object[][])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ctor", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_RouteFinder_ISpecificationImplementations_SingleResults_IntegrationTest.#TestIfRouteFinderExecuteSimpleSingleResultSpecifications(System.Type,System.String,System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "RouteCalculator.IntegrationTest.RailroadMap_Route_RouteFinder_Specifications_MultipleResults_IntegrationTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "RouteCalculator.IntegrationTest.RailroadMap_Route_ShortestRouteFinder_Specifications_IntegrationTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ctors", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_Route_ShortestRouteFinder_Specifications_IntegrationTest.#TestIfIntegrationsCanFindTheBestRoute(System.String,System.String,System.Type[],System.Object[][])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.RailroadMap_Route_ShortestRouteFinder_Specifications_IntegrationTest.#TestIfIntegrationsCanFindTheBestRoute(System.String,System.String,System.Type[],System.Object[][])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.ProgramIntegrationTest.#TestIfUseCaseNumberTenRunsCorrectly(System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.ProgramIntegrationTest.#TestIfUseCaseOneTroughFiveRunCorrectly(System.String,System.Int32[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.ProgramIntegrationTest.#TestIfUseCasesEightAndNineRunCorrectly(System.String,System.Int32[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.ProgramIntegrationTest.#TestIfUseCasesSixAndSevenRunCorrectly(System.String,System.Int32[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "RouteCalculator.IntegrationTest.ShortestLengthFinder_IntegrationTests.#TestIfItCanGetTheShortestLengthGivenAMap(System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "type", Target = "RouteCalculator.IntegrationTest.ShortestLengthFinder_IntegrationTests")]
